/*
 * Generated by erpcgen 1.13.0 on Wed May  7 16:32:16 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_wifi_client_h_)
#define _c_wifi_client_h_

#include "wifi_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief wifi identifiers */
enum _wifi_ids
{
    kwifi_service_id = 1,
    kwifi_WIFI_Scan_id = 1,
};

//! @name wifi
//@{
WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initwifi_client(erpc_client_t client);

void deinitwifi_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_wifi_client_h_
