/*
 * Generated by erpcgen 1.13.0 on Wed May  7 16:32:16 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_wifi_client.h"
#include "wifi_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
wifi_client *s_wifi_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(wifi_client, s_wifi_client);
#endif

WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks)
{
    WIFIReturnCode_t result;
    result = s_wifi_client->WIFI_Scan(pxBuffer, ucNumNetworks);

    return result;
}

void initwifi_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_wifi_client == nullptr);
    s_wifi_client = new wifi_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_wifi_client.isUsed());
    s_wifi_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitwifi_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_wifi_client != nullptr)
    {
        delete s_wifi_client;
        s_wifi_client = nullptr;
    }
#else
    s_wifi_client.destroy();
#endif
}
