/*
 * Generated by erpcgen 1.13.0 on Wed May  7 16:32:16 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_wifi_server_h_)
#define _c_wifi_server_h_

#include "wifi_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief wifi identifiers */
enum _wifi_ids
{
    kwifi_service_id = 1,
    kwifi_WIFI_Scan_id = 1,
};

//! @name wifi
//@{
WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return wifi_service service object. */
erpc_service_t create_wifi_service(void);

/*! @brief Destroy wifi_service service object. */
void destroy_wifi_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_wifi_server_h_
