/*
 * Generated by erpcgen 1.13.0 on Wed May  7 16:32:16 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_wifi_interface_hpp_)
#define _wifi_interface_hpp_

#include "wifi_common.hpp"

namespace erpcShim
{


// Abstract base class for wifi
class wifi_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_WIFI_ScanId = 1;

        virtual ~wifi_interface(void);

        virtual WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks) = 0;
private:
};
} // erpcShim


#endif // _wifi_interface_hpp_
