/*
 * Generated by erpcgen 1.13.0 on Wed May  7 16:32:16 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "wifi_server.hpp"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif



// Constant variable definitions
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_SSID_LEN
#endif
extern const uint8_t wificonfigMAX_SSID_LEN = 32;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_BSSID_LEN
#endif
extern const uint8_t wificonfigMAX_BSSID_LEN = 6;

//! @brief Function to write struct WIFIScanResult_t
static void write_WIFIScanResult_t_struct(erpc::Codec * codec, const WIFIScanResult_t * data);


// Write struct WIFIScanResult_t function implementation
static void write_WIFIScanResult_t_struct(erpc::Codec * codec, const WIFIScanResult_t * data)
{
    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->write(data->ucSSID[arrayCount0]);
    }

    codec->write(data->ucSSIDLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 6U; ++arrayCount0)
    {
        codec->write(data->ucBSSID[arrayCount0]);
    }

    codec->write(static_cast<int32_t>(data->xSecurity));

    codec->write(data->cRSSI);

    codec->write(data->ucChannel);
}



wifi_service::wifi_service(wifi_interface *_wifi_interface)
    : erpc::Service(wifi_interface::m_serviceId)
    , m_handler(_wifi_interface)
{
}

wifi_service::~wifi_service()
{
}

// return service interface handler.
wifi_interface* wifi_service::getHandler(void)
{
    return m_handler;
}

// Call the correct server shim based on method unique ID.
erpc_status_t wifi_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory, Transport * transport)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case wifi_interface::m_WIFI_ScanId:
        {
            erpcStatus = WIFI_Scan_shim(codec, messageFactory, transport, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for WIFI_Scan of wifi interface.
erpc_status_t wifi_service::WIFI_Scan_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    WIFIScanResult_t *pxBuffer = NULL;
    uint8_t ucNumNetworks;
    WIFIReturnCode_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(ucNumNetworks);

    pxBuffer = (WIFIScanResult_t *) erpc_malloc(sizeof(WIFIScanResult_t));
    if (pxBuffer == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->WIFI_Scan(pxBuffer, ucNumNetworks);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, wifi_interface::m_serviceId, wifi_interface::m_WIFI_ScanId, sequence);

        write_WIFIScanResult_t_struct(codec, pxBuffer);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    erpc_free(pxBuffer);

    return err;
}
