/*
 * Generated by erpcgen 1.13.0 on Wed May  7 16:32:16 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_wifi_common_hpp_)
#define _wifi_common_hpp_


#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_ERPCSHIM)
#define ERPC_TYPE_DEFINITIONS_ERPCSHIM

// Enumerators data types declarations
typedef enum WIFIReturnCode_t
{
    eWiFiSuccess = 0,             ///< Success
    eWiFiFailure = 1,             ///< Failure
    eWiFiTimeout = 2,             ///< Timeout
    eWiFiNotSupported = 3             ///< Not supported
} WIFIReturnCode_t;

typedef enum WIFISecurity_t
{
    eWiFiSecurityOpen = 0,             ///< Open - No Security
    eWiFiSecurityWEP = 1,                  ///< WEP Security
    eWiFiSecurityWPA = 2,                  ///< WPA Security
    eWiFiSecurityWPA2 = 3,                 ///< WPA2 Security
    eWiFiSecurityWPA2_ent = 4,             ///< WPA2 Enterprise Security
    eWiFiSecurityWPA3 = 5,                 ///< WPA3 Security
    eWiFiSecurityNotSupported = 6          ///< Unknown Security
} WIFISecurity_t;

// Aliases data types declarations
typedef struct WIFIScanResult_t WIFIScanResult_t;

// Structures/unions data types declarations
struct WIFIScanResult_t
{
    uint8_t ucSSID[32];       ///< SSID of the Wi-Fi network (binary array, not C-string)
    uint8_t ucSSIDLength; ///< SSID length
    uint8_t ucBSSID[6];      ///< BSSID of the Wi-Fi network (binary array, not C-string)
    WIFISecurity_t xSecurity;    ///< Security type of the Wi-Fi network
    int8_t cRSSI;        ///< Signal strength of the Wi-Fi network
    uint8_t ucChannel;    ///< Channel of the Wi-Fi network
};


// Constant variable declarations
extern const uint8_t wificonfigMAX_SSID_LEN;

extern const uint8_t wificonfigMAX_BSSID_LEN;

#endif // ERPC_TYPE_DEFINITIONS_ERPCSHIM


#endif // _wifi_common_hpp_
