/*
 * Generated by erpcgen 1.13.0 on Wed May  7 16:32:16 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_wifi_client_hpp_)
#define _wifi_client_hpp_

#include "wifi_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class wifi_client: public wifi_interface
{
    public:
        wifi_client(erpc::ClientManager *manager);

        virtual ~wifi_client();

        virtual WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _wifi_client_hpp_
