/*
 * Generated by erpcgen 1.13.0 on Wed May  7 16:32:16 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include "erpc_port.h"
#endif
#include "erpc_codec.hpp"
#include "wifi_client.hpp"
#include "erpc_manually_constructed.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;


// Constant variable definitions
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_SSID_LEN
#endif
extern const uint8_t wificonfigMAX_SSID_LEN = 32;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_BSSID_LEN
#endif
extern const uint8_t wificonfigMAX_BSSID_LEN = 6;

//! @brief Function to read struct WIFIScanResult_t
static void read_WIFIScanResult_t_struct(erpc::Codec * codec, WIFIScanResult_t * data);


// Read struct WIFIScanResult_t function implementation
static void read_WIFIScanResult_t_struct(erpc::Codec * codec, WIFIScanResult_t * data)
{
    int32_t _tmp_local_i32;

    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->read(data->ucSSID[arrayCount0]);
    }

    codec->read(data->ucSSIDLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 6U; ++arrayCount0)
    {
        codec->read(data->ucBSSID[arrayCount0]);
    }

    codec->read(_tmp_local_i32);
    data->xSecurity = static_cast<WIFISecurity_t>(_tmp_local_i32);

    codec->read(data->cRSSI);

    codec->read(data->ucChannel);
}




wifi_client::wifi_client(ClientManager *manager)
:m_clientManager(manager)
{
}

wifi_client::~wifi_client()
{
}

// wifi interface WIFI_Scan function client shim.
WIFIReturnCode_t wifi_client::WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    WIFIReturnCode_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_WIFI_ScanId, request.getSequence());

        codec->write(ucNumNetworks);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        read_WIFIScanResult_t_struct(codec, pxBuffer);

        codec->read(_tmp_local_i32);
        result = static_cast<WIFIReturnCode_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_WIFI_ScanId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (WIFIReturnCode_t) -1;
    }

    return result;
}
