/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include <new>
#include "c_wifi_server.h"
#include "wifi_server.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


class wifi_server: public wifi_interface
{
    public:
        virtual ~wifi_server() {};


        WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks)
        {
            WIFIReturnCode_t result;
            result = ::WIFI_Scan(pxBuffer, ucNumNetworks);

            return result;
        }

        WIFIReturnCode_t WIFI_ScanExtended(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks, const WIFIScanExtendedConfig_t * pxScanConfigExtended)
        {
            WIFIReturnCode_t result;
            result = ::WIFI_ScanExtended(pxBuffer, ucNumNetworks, pxScanConfigExtended);

            return result;
        }

        WIFIReturnCode_t WIFI_ConnectAP(const WIFINetworkParams_t * pxNetworkParams)
        {
            WIFIReturnCode_t result;
            result = ::WIFI_ConnectAP(pxNetworkParams);

            return result;
        }

        WIFIReturnCode_t WIFI_ConnectAPExt(const WIFINetworkParamsExt_t * pxNetworkParamsExt)
        {
            WIFIReturnCode_t result;
            result = ::WIFI_ConnectAPExt(pxNetworkParamsExt);

            return result;
        }

        WIFIReturnCode_t WIFI_Disconnect(void)
        {
            WIFIReturnCode_t result;
            result = ::WIFI_Disconnect();

            return result;
        }

        WIFIReturnCode_t WIFI_GetConnectionInfo(WIFIConnectionInfo_t * pxConnectionInfo)
        {
            WIFIReturnCode_t result;
            result = ::WIFI_GetConnectionInfo(pxConnectionInfo);

            return result;
        }
};

ERPC_MANUALLY_CONSTRUCTED_STATIC(wifi_service, s_wifi_service);
ERPC_MANUALLY_CONSTRUCTED_STATIC(wifi_server, s_wifi_server);

erpc_service_t create_wifi_service(void)
{
    erpc_service_t service;

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    service = new (nothrow) wifi_service(new (nothrow)wifi_server());
#else
    if (s_wifi_service.isUsed())
    {
        service = NULL;
    }
    else
    {
        s_wifi_server.construct();
        s_wifi_service.construct(s_wifi_server.get());
        service = s_wifi_service.get();
    }
#endif

    return service;
}

void destroy_wifi_service(erpc_service_t service)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (service)
    {
        delete (wifi_server *)(((wifi_service *)service)->getHandler());
        delete (wifi_service *)service;
    }
#else
    (void)service;
    erpc_assert(service == s_wifi_service.get());
    s_wifi_service.destroy();
    s_wifi_server.destroy();
#endif
}
