/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_wifi_client_h_)
#define _c_wifi_client_h_

#include "wifi_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief wifi identifiers */
enum _wifi_ids
{
    kwifi_service_id = 1,
    kwifi_WIFI_Scan_id = 1,
    kwifi_WIFI_ScanExtended_id = 2,
    kwifi_WIFI_ConnectAP_id = 3,
    kwifi_WIFI_ConnectAPExt_id = 4,
    kwifi_WIFI_Disconnect_id = 5,
    kwifi_WIFI_GetConnectionInfo_id = 6,
};

//! @name wifi
//@{
WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks);

WIFIReturnCode_t WIFI_ScanExtended(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks, const WIFIScanExtendedConfig_t * pxScanConfigExtended);

WIFIReturnCode_t WIFI_ConnectAP(const WIFINetworkParams_t * pxNetworkParams);

WIFIReturnCode_t WIFI_ConnectAPExt(const WIFINetworkParamsExt_t * pxNetworkParamsExt);

WIFIReturnCode_t WIFI_Disconnect(void);

WIFIReturnCode_t WIFI_GetConnectionInfo(WIFIConnectionInfo_t * pxConnectionInfo);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initwifi_client(erpc_client_t client);

void deinitwifi_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_wifi_client_h_
