/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_wifi_client.h"
#include "wifi_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
wifi_client *s_wifi_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(wifi_client, s_wifi_client);
#endif

WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks)
{
    WIFIReturnCode_t result;
    result = s_wifi_client->WIFI_Scan(pxBuffer, ucNumNetworks);

    return result;
}

WIFIReturnCode_t WIFI_ScanExtended(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks, const WIFIScanExtendedConfig_t * pxScanConfigExtended)
{
    WIFIReturnCode_t result;
    result = s_wifi_client->WIFI_ScanExtended(pxBuffer, ucNumNetworks, pxScanConfigExtended);

    return result;
}

WIFIReturnCode_t WIFI_ConnectAP(const WIFINetworkParams_t * pxNetworkParams)
{
    WIFIReturnCode_t result;
    result = s_wifi_client->WIFI_ConnectAP(pxNetworkParams);

    return result;
}

WIFIReturnCode_t WIFI_ConnectAPExt(const WIFINetworkParamsExt_t * pxNetworkParamsExt)
{
    WIFIReturnCode_t result;
    result = s_wifi_client->WIFI_ConnectAPExt(pxNetworkParamsExt);

    return result;
}

WIFIReturnCode_t WIFI_Disconnect(void)
{
    WIFIReturnCode_t result;
    result = s_wifi_client->WIFI_Disconnect();

    return result;
}

WIFIReturnCode_t WIFI_GetConnectionInfo(WIFIConnectionInfo_t * pxConnectionInfo)
{
    WIFIReturnCode_t result;
    result = s_wifi_client->WIFI_GetConnectionInfo(pxConnectionInfo);

    return result;
}

void initwifi_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_wifi_client == nullptr);
    s_wifi_client = new wifi_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_wifi_client.isUsed());
    s_wifi_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitwifi_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_wifi_client != nullptr)
    {
        delete s_wifi_client;
        s_wifi_client = nullptr;
    }
#else
    s_wifi_client.destroy();
#endif
}
