/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_wifi_interface_hpp_)
#define _wifi_interface_hpp_

#include "wifi_common.hpp"

namespace erpcShim
{


// Abstract base class for wifi
class wifi_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_WIFI_ScanId = 1;
        static const uint8_t m_WIFI_ScanExtendedId = 2;
        static const uint8_t m_WIFI_ConnectAPId = 3;
        static const uint8_t m_WIFI_ConnectAPExtId = 4;
        static const uint8_t m_WIFI_DisconnectId = 5;
        static const uint8_t m_WIFI_GetConnectionInfoId = 6;

        virtual ~wifi_interface(void);

        virtual WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks) = 0;

        virtual WIFIReturnCode_t WIFI_ScanExtended(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks, const WIFIScanExtendedConfig_t * pxScanConfigExtended) = 0;

        virtual WIFIReturnCode_t WIFI_ConnectAP(const WIFINetworkParams_t * pxNetworkParams) = 0;

        virtual WIFIReturnCode_t WIFI_ConnectAPExt(const WIFINetworkParamsExt_t * pxNetworkParamsExt) = 0;

        virtual WIFIReturnCode_t WIFI_Disconnect(void) = 0;

        virtual WIFIReturnCode_t WIFI_GetConnectionInfo(WIFIConnectionInfo_t * pxConnectionInfo) = 0;
private:
};
} // erpcShim


#endif // _wifi_interface_hpp_
