/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include "erpc_port.h"
#endif
#include "erpc_codec.hpp"
#include "wifi_client.hpp"
#include "erpc_manually_constructed.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;


// Constant variable definitions
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_SSID_LEN
#endif
extern const uint8_t wificonfigMAX_SSID_LEN = 32;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_BSSID_LEN
#endif
extern const uint8_t wificonfigMAX_BSSID_LEN = 6;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_PASSPHRASE_LEN
#endif
extern const uint8_t wificonfigMAX_PASSPHRASE_LEN = 128;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_WEPKEYS
#endif
extern const uint8_t wificonfigMAX_WEPKEYS = 4;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_WEPKEY_LEN
#endif
extern const uint8_t wificonfigMAX_WEPKEY_LEN = 26;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_SAE_GROUPS_LEN
#endif
extern const uint8_t wificonfigMAX_SAE_GROUPS_LEN = 20;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_ENT_IDENTITY_LEN
#endif
extern const uint8_t wificonfigMAX_ENT_IDENTITY_LEN = 32;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_ENT_PASSWORD_LEN
#endif
extern const uint8_t wificonfigMAX_ENT_PASSWORD_LEN = 32;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_CERT_LEN
#endif
extern const uint16_t wificonfigMAX_CERT_LEN = 4096;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_PRIV_KEY_LEN
#endif
extern const uint16_t wificonfigMAX_PRIV_KEY_LEN = 4096;

//! @brief Function to write struct WIFIScanConfig_t
static void write_WIFIScanConfig_t_struct(erpc::Codec * codec, const WIFIScanConfig_t * data);

//! @brief Function to write struct WIFIScanExtendedConfig_t
static void write_WIFIScanExtendedConfig_t_struct(erpc::Codec * codec, const WIFIScanExtendedConfig_t * data);

//! @brief Function to write struct WIFINetworkParams_t
static void write_WIFINetworkParams_t_struct(erpc::Codec * codec, const WIFINetworkParams_t * data);

//! @brief Function to write struct WIFIEnterpriseNetParams_t
static void write_WIFIEnterpriseNetParams_t_struct(erpc::Codec * codec, const WIFIEnterpriseNetParams_t * data);

//! @brief Function to write struct WIFINetworkParamsExt_t
static void write_WIFINetworkParamsExt_t_struct(erpc::Codec * codec, const WIFINetworkParamsExt_t * data);


// Write struct WIFIScanConfig_t function implementation
static void write_WIFIScanConfig_t_struct(erpc::Codec * codec, const WIFIScanConfig_t * data)
{
    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->write(data->ucSSID[arrayCount0]);
    }

    codec->write(data->ucSSIDLength);

    codec->write(data->ucChannel);
}

// Write struct WIFIScanExtendedConfig_t function implementation
static void write_WIFIScanExtendedConfig_t_struct(erpc::Codec * codec, const WIFIScanExtendedConfig_t * data)
{
    if(NULL == data)
    {
        return;
    }

    write_WIFIScanConfig_t_struct(codec, &(data->pxScanConfig));

    codec->write(static_cast<int32_t>(data->ucBand));
}

// Write struct WIFINetworkParams_t function implementation
static void write_WIFINetworkParams_t_struct(erpc::Codec * codec, const WIFINetworkParams_t * data)
{
    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->write(data->ucSSID[arrayCount0]);
    }

    codec->write(data->ucSSIDLength);

    codec->write(static_cast<int32_t>(data->xSecurity));

    codec->write(data->ucDefaultWEPKeyIndex);

    codec->write(data->ucChannel);
}

// Write struct WIFIEnterpriseNetParams_t function implementation
static void write_WIFIEnterpriseNetParams_t_struct(erpc::Codec * codec, const WIFIEnterpriseNetParams_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->write(static_cast<int32_t>(data->ucEntAuthType));

    codec->write(static_cast<int32_t>(data->ucEntAuthProto));

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->write(data->ucID[arrayCount0]);
    }

    codec->write(data->ucIDLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->write(data->ucPassword[arrayCount0]);
    }

    codec->write(data->ucPasswordLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 4096U; ++arrayCount0)
    {
        codec->write(data->ucCert[arrayCount0]);
    }

    codec->write(data->ucCertLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 4096U; ++arrayCount0)
    {
        codec->write(data->ucPrivKey[arrayCount0]);
    }

    codec->write(data->ucPrivKeyLength);
}

// Write struct WIFINetworkParamsExt_t function implementation
static void write_WIFINetworkParamsExt_t_struct(erpc::Codec * codec, const WIFINetworkParamsExt_t * data)
{
    if(NULL == data)
    {
        return;
    }

    write_WIFINetworkParams_t_struct(codec, &(data->xNetworkParams));

    write_WIFIEnterpriseNetParams_t_struct(codec, &(data->xEntNetParams));

    codec->write(static_cast<int32_t>(data->ucBand));

    codec->write(static_cast<int32_t>(data->ucWiFi_mode));

    codec->write(data->hidden_ssid);

    codec->write(static_cast<int32_t>(data->pmf));

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 20U; ++arrayCount0)
    {
        codec->write(data->sae_groups[arrayCount0]);
    }
}


//! @brief Function to read struct WIFIScanResult_t
static void read_WIFIScanResult_t_struct(erpc::Codec * codec, WIFIScanResult_t * data);

//! @brief Function to read struct WIFIConnectionInfo_t
static void read_WIFIConnectionInfo_t_struct(erpc::Codec * codec, WIFIConnectionInfo_t * data);


// Read struct WIFIScanResult_t function implementation
static void read_WIFIScanResult_t_struct(erpc::Codec * codec, WIFIScanResult_t * data)
{
    int32_t _tmp_local_i32;

    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->read(data->ucSSID[arrayCount0]);
    }

    codec->read(data->ucSSIDLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 6U; ++arrayCount0)
    {
        codec->read(data->ucBSSID[arrayCount0]);
    }

    codec->read(_tmp_local_i32);
    data->xSecurity = static_cast<WIFISecurity_t>(_tmp_local_i32);

    codec->read(data->cRSSI);

    codec->read(data->ucChannel);
}

// Read struct WIFIConnectionInfo_t function implementation
static void read_WIFIConnectionInfo_t_struct(erpc::Codec * codec, WIFIConnectionInfo_t * data)
{
    int32_t _tmp_local_i32;

    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->read(data->ucSSID[arrayCount0]);
    }

    codec->read(data->ucSSIDLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 6U; ++arrayCount0)
    {
        codec->read(data->ucBSSID[arrayCount0]);
    }

    codec->read(_tmp_local_i32);
    data->xSecurity = static_cast<WIFISecurity_t>(_tmp_local_i32);

    codec->read(data->ucChannel);
}




wifi_client::wifi_client(ClientManager *manager)
:m_clientManager(manager)
{
}

wifi_client::~wifi_client()
{
}

// wifi interface WIFI_Scan function client shim.
WIFIReturnCode_t wifi_client::WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    WIFIReturnCode_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_WIFI_ScanId, request.getSequence());

        codec->write(ucNumNetworks);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        read_WIFIScanResult_t_struct(codec, pxBuffer);

        codec->read(_tmp_local_i32);
        result = static_cast<WIFIReturnCode_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_WIFI_ScanId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (WIFIReturnCode_t) -1;
    }

    return result;
}

// wifi interface WIFI_ScanExtended function client shim.
WIFIReturnCode_t wifi_client::WIFI_ScanExtended(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks, const WIFIScanExtendedConfig_t * pxScanConfigExtended)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    WIFIReturnCode_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_WIFI_ScanExtendedId, request.getSequence());

        codec->write(ucNumNetworks);

        write_WIFIScanExtendedConfig_t_struct(codec, pxScanConfigExtended);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        read_WIFIScanResult_t_struct(codec, pxBuffer);

        codec->read(_tmp_local_i32);
        result = static_cast<WIFIReturnCode_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_WIFI_ScanExtendedId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (WIFIReturnCode_t) -1;
    }

    return result;
}

// wifi interface WIFI_ConnectAP function client shim.
WIFIReturnCode_t wifi_client::WIFI_ConnectAP(const WIFINetworkParams_t * pxNetworkParams)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    WIFIReturnCode_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_WIFI_ConnectAPId, request.getSequence());

        write_WIFINetworkParams_t_struct(codec, pxNetworkParams);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<WIFIReturnCode_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_WIFI_ConnectAPId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (WIFIReturnCode_t) -1;
    }

    return result;
}

// wifi interface WIFI_ConnectAPExt function client shim.
WIFIReturnCode_t wifi_client::WIFI_ConnectAPExt(const WIFINetworkParamsExt_t * pxNetworkParamsExt)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    WIFIReturnCode_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_WIFI_ConnectAPExtId, request.getSequence());

        write_WIFINetworkParamsExt_t_struct(codec, pxNetworkParamsExt);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<WIFIReturnCode_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_WIFI_ConnectAPExtId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (WIFIReturnCode_t) -1;
    }

    return result;
}

// wifi interface WIFI_Disconnect function client shim.
WIFIReturnCode_t wifi_client::WIFI_Disconnect(void)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    WIFIReturnCode_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_WIFI_DisconnectId, request.getSequence());

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<WIFIReturnCode_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_WIFI_DisconnectId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (WIFIReturnCode_t) -1;
    }

    return result;
}

// wifi interface WIFI_GetConnectionInfo function client shim.
WIFIReturnCode_t wifi_client::WIFI_GetConnectionInfo(WIFIConnectionInfo_t * pxConnectionInfo)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    WIFIReturnCode_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_WIFI_GetConnectionInfoId, request.getSequence());

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        read_WIFIConnectionInfo_t_struct(codec, pxConnectionInfo);

        codec->read(_tmp_local_i32);
        result = static_cast<WIFIReturnCode_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_WIFI_GetConnectionInfoId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (WIFIReturnCode_t) -1;
    }

    return result;
}
