/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_wifi_common_hpp_)
#define _wifi_common_hpp_


#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_ERPCSHIM)
#define ERPC_TYPE_DEFINITIONS_ERPCSHIM

// Enumerators data types declarations
typedef enum WIFIReturnCode_t
{
    eWiFiSuccess = 0,             ///< Success
    eWiFiFailure = 1,             ///< Failure
    eWiFiTimeout = 2,             ///< Timeout
    eWiFiNotSupported = 3             ///< Not supported
} WIFIReturnCode_t;

typedef enum WIFISecurity_t
{
    eWiFiSecurityOpen = 0,             ///< Open - No Security
    eWiFiSecurityWEP = 1,                  ///< WEP Security
    eWiFiSecurityWPA = 2,                  ///< WPA Security
    eWiFiSecurityWPA2 = 3,                 ///< WPA2 Security
    eWiFiSecurityWPA2_ent = 4,             ///< WPA2 Enterprise Security
    eWiFiSecurityWPA3 = 5,                 ///< WPA3 Security
    eWiFiSecurityNotSupported = 6          ///< Unknown Security
} WIFISecurity_t;

typedef enum WIFIBand_t
{
    eWiFiBand2G = 0,                   ///< 2.4G band
    eWiFiBand5G = 1,                       ///< 5G band
    eWiFiBandDual = 2,                     ///< Dual band
    eWiFiBandMax = 3                       ///< Unsupported
} WIFIBand_t;

typedef enum WIFIPmf_t
{
    PMF_NONE = 0,
    PMF_CAPABLE = 1,
    PMF_REQUIRED = 2,
    PMF_DEFAULT = 3
} WIFIPmf_t;

typedef enum WIFIEntAuthTypeExt_t
{
    ENT_AUTH_TYPE_NONE = 0,
    ENT_AUTH_TYPE_PEAP_TTLS_FAST = 1,
    ENT_AUTH_TYPE_PEAP = 2,
    ENT_AUTH_TYPE_TTLS = 3,
    ENT_AUTH_TYPE_FAST = 4,
    ENT_AUTH_TYPE_TLS = 5,
    ENT_AUTH_TYPE_UNSUPPORTED = 6
} WIFIEntAuthTypeExt_t;

typedef enum WIFIEntAuthProtoExt_t
{
    ENT_AUTH_PROTO_NONE = 0,
    ENT_AUTH_PROTO_MSCHAPv2_GTC = 1,
    ENT_AUTH_PROTO_MSCHAPv2 = 2,
    ENT_AUTH_PROTO_GTC = 3,
    ENT_AUTH_PROTO_TLS = 4,
    ENT_AUTH_PROTO_UNSUPPORTED = 5
} WIFIEntAuthProtoExt_t;

typedef enum e_wifi_phy_mode_ext_t
{
    WIFI_PHY_MODE_AUTO_STA = 0,
    WIFI_PHY_MODE_BGN = 0,
    WIFI_PHY_MODE_GN = 1,
    WIFI_PHY_MODE_BG = 2,
    WIFI_PHY_MODE_N_ONLY = 3,
    WIFI_PHY_MODE_G_ONLY = 4,
    WIFI_PHY_MODE_B_ONLY = 5,
    WIFI_PHY_MODE_AN = 6,
    WIFI_PHY_MODE_A_ONLY = 7,
    WIFI_PHY_MODE_N_ONLY_5G = 8,
    WIFI_PHY_MODE_MAX = 9
} e_wifi_phy_mode_ext_t;

// Aliases data types declarations
typedef struct WIFINetworkParams_t WIFINetworkParams_t;
typedef struct WIFIEnterpriseNetParams_t WIFIEnterpriseNetParams_t;
typedef struct WIFINetworkParamsExt_t WIFINetworkParamsExt_t;
typedef struct WIFIScanConfig_t WIFIScanConfig_t;
typedef struct WIFIScanExtendedConfig_t WIFIScanExtendedConfig_t;
typedef struct WIFIConnectionInfo_t WIFIConnectionInfo_t;
typedef struct WIFIScanResult_t WIFIScanResult_t;
typedef struct WIFIWEPKey_t WIFIWEPKey_t;
typedef struct WIFIWPAPassphrase_t WIFIWPAPassphrase_t;

// Structures/unions data types declarations
struct WIFINetworkParams_t
{
    uint8_t ucSSID[32];       			///< SSID of the Wi-Fi network (binary array, not C-string)
    uint8_t ucSSIDLength; 			///< SSID length
    WIFISecurity_t xSecurity;    			///< Wi-Fi Security
    uint8_t ucDefaultWEPKeyIndex;	///< Default WEP key index
    uint8_t ucChannel;              ///< Channel number
};

struct WIFIEnterpriseNetParams_t
{
    WIFIEntAuthTypeExt_t ucEntAuthType;
    WIFIEntAuthProtoExt_t ucEntAuthProto;
    uint8_t ucID[32];
    uint8_t ucIDLength;
    uint8_t ucPassword[32];
    uint8_t ucPasswordLength;
    uint8_t ucCert[4096];
    uint16_t ucCertLength;
    uint8_t ucPrivKey[4096];
    uint8_t ucPrivKeyLength;
};

struct WIFINetworkParamsExt_t
{
    WIFINetworkParams_t xNetworkParams; ///< Basic configuration
    WIFIEnterpriseNetParams_t xEntNetParams; 	///< Enterprise security configuration
    WIFIBand_t ucBand;         ///< Band to configure
    e_wifi_phy_mode_ext_t ucWiFi_mode;    ///< Wi-Fi PHY mode to configure (a, b, g ,n, ...)
    bool hidden_ssid;    ///< AP is using hidden SSID
    WIFIPmf_t pmf;            ///< Protected Management Frame mode
    uint8_t sae_groups[20];		///< String contains all the WPA3 sae group ids
};

struct WIFIScanConfig_t
{
    uint8_t ucSSID[32]; 	///< SSID for targeted scan (binary array, not C-string)
    uint8_t ucSSIDLength;                   	///< SSID length, 0 if broadcast scan
    uint8_t ucChannel;                      	///< Channel to scan (0 means all channels)
};

struct WIFIScanExtendedConfig_t
{
    WIFIScanConfig_t pxScanConfig; ///< Wi-Fi scan configuration
    WIFIBand_t ucBand;       ///< Band to scan
};

struct WIFIConnectionInfo_t
{
    uint8_t ucSSID[32];       ///< SSID of the Wi-Fi network (binary array, not C-string)
    uint8_t ucSSIDLength; ///< SSID length
    uint8_t ucBSSID[6];      ///< BSSID of the Wi-Fi network (binary array, not C-string)
    WIFISecurity_t xSecurity;    ///< Wi-Fi Security
    uint8_t ucChannel;    ///< Channel info
};

struct WIFIScanResult_t
{
    uint8_t ucSSID[32];       ///< SSID of the Wi-Fi network (binary array, not C-string)
    uint8_t ucSSIDLength; ///< SSID length
    uint8_t ucBSSID[6];      ///< BSSID of the Wi-Fi network (binary array, not C-string)
    WIFISecurity_t xSecurity;    ///< Security type of the Wi-Fi network
    int8_t cRSSI;        ///< Signal strength of the Wi-Fi network
    uint8_t ucChannel;    ///< Channel of the Wi-Fi network
};

struct WIFIWEPKey_t
{
    uint8_t cKey[26]; 		///< WEP key (binary array, not C-string)
    uint8_t ucLength;   ///< Key length
};

struct WIFIWPAPassphrase_t
{
    uint8_t cPassphrase[128]; ///< WPA passphrase (binary array, not C-string)
    uint8_t ucLength;    ///< Passphrase length (must be between 8 and 64 inclusive)
};


// Constant variable declarations
extern const uint8_t wificonfigMAX_SSID_LEN;

extern const uint8_t wificonfigMAX_BSSID_LEN;

extern const uint8_t wificonfigMAX_PASSPHRASE_LEN;

extern const uint8_t wificonfigMAX_WEPKEYS;

extern const uint8_t wificonfigMAX_WEPKEY_LEN;

extern const uint8_t wificonfigMAX_SAE_GROUPS_LEN;

extern const uint8_t wificonfigMAX_ENT_IDENTITY_LEN;

extern const uint8_t wificonfigMAX_ENT_PASSWORD_LEN;

extern const uint16_t wificonfigMAX_CERT_LEN;

extern const uint16_t wificonfigMAX_PRIV_KEY_LEN;

#endif // ERPC_TYPE_DEFINITIONS_ERPCSHIM


#endif // _wifi_common_hpp_
