/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_wifi_client_hpp_)
#define _wifi_client_hpp_

#include "wifi_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class wifi_client: public wifi_interface
{
    public:
        wifi_client(erpc::ClientManager *manager);

        virtual ~wifi_client();

        virtual WIFIReturnCode_t WIFI_Scan(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks);

        virtual WIFIReturnCode_t WIFI_ScanExtended(WIFIScanResult_t * pxBuffer, uint8_t ucNumNetworks, const WIFIScanExtendedConfig_t * pxScanConfigExtended);

        virtual WIFIReturnCode_t WIFI_ConnectAP(const WIFINetworkParams_t * pxNetworkParams);

        virtual WIFIReturnCode_t WIFI_ConnectAPExt(const WIFINetworkParamsExt_t * pxNetworkParamsExt);

        virtual WIFIReturnCode_t WIFI_Disconnect(void);

        virtual WIFIReturnCode_t WIFI_GetConnectionInfo(WIFIConnectionInfo_t * pxConnectionInfo);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _wifi_client_hpp_
