/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_wifi_server_hpp_)
#define _wifi_server_hpp_

#include "wifi_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for wifi.
 */
class wifi_service : public erpc::Service
{
public:
    wifi_service(wifi_interface *_wifi_interface);

    virtual ~wifi_service();

    /*! @brief return service interface handler. */
    wifi_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    wifi_interface *m_handler;
    /*! @brief Server shim for WIFI_Scan of wifi interface. */
    erpc_status_t WIFI_Scan_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for WIFI_ScanExtended of wifi interface. */
    erpc_status_t WIFI_ScanExtended_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for WIFI_ConnectAP of wifi interface. */
    erpc_status_t WIFI_ConnectAP_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for WIFI_ConnectAPExt of wifi interface. */
    erpc_status_t WIFI_ConnectAPExt_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for WIFI_Disconnect of wifi interface. */
    erpc_status_t WIFI_Disconnect_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for WIFI_GetConnectionInfo of wifi interface. */
    erpc_status_t WIFI_GetConnectionInfo_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _wifi_server_hpp_
