/*
 * Generated by erpcgen 1.13.0 on Wed May 14 15:12:17 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "wifi_server.hpp"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif



// Constant variable definitions
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_SSID_LEN
#endif
extern const uint8_t wificonfigMAX_SSID_LEN = 32;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_BSSID_LEN
#endif
extern const uint8_t wificonfigMAX_BSSID_LEN = 6;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_PASSPHRASE_LEN
#endif
extern const uint8_t wificonfigMAX_PASSPHRASE_LEN = 128;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_WEPKEYS
#endif
extern const uint8_t wificonfigMAX_WEPKEYS = 4;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_WEPKEY_LEN
#endif
extern const uint8_t wificonfigMAX_WEPKEY_LEN = 26;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_SAE_GROUPS_LEN
#endif
extern const uint8_t wificonfigMAX_SAE_GROUPS_LEN = 20;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_ENT_IDENTITY_LEN
#endif
extern const uint8_t wificonfigMAX_ENT_IDENTITY_LEN = 32;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_ENT_PASSWORD_LEN
#endif
extern const uint8_t wificonfigMAX_ENT_PASSWORD_LEN = 32;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_CERT_LEN
#endif
extern const uint16_t wificonfigMAX_CERT_LEN = 4096;
#if defined(__MINGW32__)
__declspec( selectany )
#else
#pragma weak wificonfigMAX_PRIV_KEY_LEN
#endif
extern const uint16_t wificonfigMAX_PRIV_KEY_LEN = 4096;

//! @brief Function to read struct WIFIScanConfig_t
static void read_WIFIScanConfig_t_struct(erpc::Codec * codec, WIFIScanConfig_t * data);

//! @brief Function to read struct WIFIScanExtendedConfig_t
static void read_WIFIScanExtendedConfig_t_struct(erpc::Codec * codec, WIFIScanExtendedConfig_t * data);

//! @brief Function to read struct WIFINetworkParams_t
static void read_WIFINetworkParams_t_struct(erpc::Codec * codec, WIFINetworkParams_t * data);

//! @brief Function to read struct WIFIEnterpriseNetParams_t
static void read_WIFIEnterpriseNetParams_t_struct(erpc::Codec * codec, WIFIEnterpriseNetParams_t * data);

//! @brief Function to read struct WIFINetworkParamsExt_t
static void read_WIFINetworkParamsExt_t_struct(erpc::Codec * codec, WIFINetworkParamsExt_t * data);


// Read struct WIFIScanConfig_t function implementation
static void read_WIFIScanConfig_t_struct(erpc::Codec * codec, WIFIScanConfig_t * data)
{
    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->read(data->ucSSID[arrayCount0]);
    }

    codec->read(data->ucSSIDLength);

    codec->read(data->ucChannel);
}

// Read struct WIFIScanExtendedConfig_t function implementation
static void read_WIFIScanExtendedConfig_t_struct(erpc::Codec * codec, WIFIScanExtendedConfig_t * data)
{
    int32_t _tmp_local_i32;

    if(NULL == data)
    {
        return;
    }

    read_WIFIScanConfig_t_struct(codec, &(data->pxScanConfig));

    codec->read(_tmp_local_i32);
    data->ucBand = static_cast<WIFIBand_t>(_tmp_local_i32);
}

// Read struct WIFINetworkParams_t function implementation
static void read_WIFINetworkParams_t_struct(erpc::Codec * codec, WIFINetworkParams_t * data)
{
    int32_t _tmp_local_i32;

    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->read(data->ucSSID[arrayCount0]);
    }

    codec->read(data->ucSSIDLength);

    codec->read(_tmp_local_i32);
    data->xSecurity = static_cast<WIFISecurity_t>(_tmp_local_i32);

    codec->read(data->ucDefaultWEPKeyIndex);

    codec->read(data->ucChannel);
}

// Read struct WIFIEnterpriseNetParams_t function implementation
static void read_WIFIEnterpriseNetParams_t_struct(erpc::Codec * codec, WIFIEnterpriseNetParams_t * data)
{
    int32_t _tmp_local_i32;

    if(NULL == data)
    {
        return;
    }

    codec->read(_tmp_local_i32);
    data->ucEntAuthType = static_cast<WIFIEntAuthTypeExt_t>(_tmp_local_i32);

    codec->read(_tmp_local_i32);
    data->ucEntAuthProto = static_cast<WIFIEntAuthProtoExt_t>(_tmp_local_i32);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->read(data->ucID[arrayCount0]);
    }

    codec->read(data->ucIDLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->read(data->ucPassword[arrayCount0]);
    }

    codec->read(data->ucPasswordLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 4096U; ++arrayCount0)
    {
        codec->read(data->ucCert[arrayCount0]);
    }

    codec->read(data->ucCertLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 4096U; ++arrayCount0)
    {
        codec->read(data->ucPrivKey[arrayCount0]);
    }

    codec->read(data->ucPrivKeyLength);
}

// Read struct WIFINetworkParamsExt_t function implementation
static void read_WIFINetworkParamsExt_t_struct(erpc::Codec * codec, WIFINetworkParamsExt_t * data)
{
    int32_t _tmp_local_i32;

    if(NULL == data)
    {
        return;
    }

    read_WIFINetworkParams_t_struct(codec, &(data->xNetworkParams));

    read_WIFIEnterpriseNetParams_t_struct(codec, &(data->xEntNetParams));

    codec->read(_tmp_local_i32);
    data->ucBand = static_cast<WIFIBand_t>(_tmp_local_i32);

    codec->read(_tmp_local_i32);
    data->ucWiFi_mode = static_cast<e_wifi_phy_mode_ext_t>(_tmp_local_i32);

    codec->read(data->hidden_ssid);

    codec->read(_tmp_local_i32);
    data->pmf = static_cast<WIFIPmf_t>(_tmp_local_i32);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 20U; ++arrayCount0)
    {
        codec->read(data->sae_groups[arrayCount0]);
    }
}


//! @brief Function to write struct WIFIScanResult_t
static void write_WIFIScanResult_t_struct(erpc::Codec * codec, const WIFIScanResult_t * data);

//! @brief Function to write struct WIFIConnectionInfo_t
static void write_WIFIConnectionInfo_t_struct(erpc::Codec * codec, const WIFIConnectionInfo_t * data);


// Write struct WIFIScanResult_t function implementation
static void write_WIFIScanResult_t_struct(erpc::Codec * codec, const WIFIScanResult_t * data)
{
    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->write(data->ucSSID[arrayCount0]);
    }

    codec->write(data->ucSSIDLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 6U; ++arrayCount0)
    {
        codec->write(data->ucBSSID[arrayCount0]);
    }

    codec->write(static_cast<int32_t>(data->xSecurity));

    codec->write(data->cRSSI);

    codec->write(data->ucChannel);
}

// Write struct WIFIConnectionInfo_t function implementation
static void write_WIFIConnectionInfo_t_struct(erpc::Codec * codec, const WIFIConnectionInfo_t * data)
{
    if(NULL == data)
    {
        return;
    }

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 32U; ++arrayCount0)
    {
        codec->write(data->ucSSID[arrayCount0]);
    }

    codec->write(data->ucSSIDLength);

    for (uint32_t arrayCount0 = 0U; arrayCount0 < 6U; ++arrayCount0)
    {
        codec->write(data->ucBSSID[arrayCount0]);
    }

    codec->write(static_cast<int32_t>(data->xSecurity));

    codec->write(data->ucChannel);
}



wifi_service::wifi_service(wifi_interface *_wifi_interface)
    : erpc::Service(wifi_interface::m_serviceId)
    , m_handler(_wifi_interface)
{
}

wifi_service::~wifi_service()
{
}

// return service interface handler.
wifi_interface* wifi_service::getHandler(void)
{
    return m_handler;
}

// Call the correct server shim based on method unique ID.
erpc_status_t wifi_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory, Transport * transport)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case wifi_interface::m_WIFI_ScanId:
        {
            erpcStatus = WIFI_Scan_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case wifi_interface::m_WIFI_ScanExtendedId:
        {
            erpcStatus = WIFI_ScanExtended_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case wifi_interface::m_WIFI_ConnectAPId:
        {
            erpcStatus = WIFI_ConnectAP_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case wifi_interface::m_WIFI_ConnectAPExtId:
        {
            erpcStatus = WIFI_ConnectAPExt_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case wifi_interface::m_WIFI_DisconnectId:
        {
            erpcStatus = WIFI_Disconnect_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case wifi_interface::m_WIFI_GetConnectionInfoId:
        {
            erpcStatus = WIFI_GetConnectionInfo_shim(codec, messageFactory, transport, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for WIFI_Scan of wifi interface.
erpc_status_t wifi_service::WIFI_Scan_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    WIFIScanResult_t *pxBuffer = NULL;
    uint8_t ucNumNetworks;
    WIFIReturnCode_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(ucNumNetworks);

    pxBuffer = (WIFIScanResult_t *) erpc_malloc(sizeof(WIFIScanResult_t));
    if (pxBuffer == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->WIFI_Scan(pxBuffer, ucNumNetworks);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, wifi_interface::m_serviceId, wifi_interface::m_WIFI_ScanId, sequence);

        write_WIFIScanResult_t_struct(codec, pxBuffer);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    erpc_free(pxBuffer);

    return err;
}

// Server shim for WIFI_ScanExtended of wifi interface.
erpc_status_t wifi_service::WIFI_ScanExtended_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    WIFIScanResult_t *pxBuffer = NULL;
    uint8_t ucNumNetworks;
    WIFIScanExtendedConfig_t *pxScanConfigExtended = NULL;
    pxScanConfigExtended = (WIFIScanExtendedConfig_t *) erpc_malloc(sizeof(WIFIScanExtendedConfig_t));
    if (pxScanConfigExtended == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    WIFIReturnCode_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(ucNumNetworks);

    read_WIFIScanExtendedConfig_t_struct(codec, pxScanConfigExtended);

    pxBuffer = (WIFIScanResult_t *) erpc_malloc(sizeof(WIFIScanResult_t));
    if (pxBuffer == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->WIFI_ScanExtended(pxBuffer, ucNumNetworks, pxScanConfigExtended);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, wifi_interface::m_serviceId, wifi_interface::m_WIFI_ScanExtendedId, sequence);

        write_WIFIScanResult_t_struct(codec, pxBuffer);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    erpc_free(pxBuffer);

    erpc_free(pxScanConfigExtended);

    return err;
}

// Server shim for WIFI_ConnectAP of wifi interface.
erpc_status_t wifi_service::WIFI_ConnectAP_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    WIFINetworkParams_t *pxNetworkParams = NULL;
    pxNetworkParams = (WIFINetworkParams_t *) erpc_malloc(sizeof(WIFINetworkParams_t));
    if (pxNetworkParams == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    WIFIReturnCode_t result;

    // startReadMessage() was already called before this shim was invoked.

    read_WIFINetworkParams_t_struct(codec, pxNetworkParams);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->WIFI_ConnectAP(pxNetworkParams);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, wifi_interface::m_serviceId, wifi_interface::m_WIFI_ConnectAPId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    erpc_free(pxNetworkParams);

    return err;
}

// Server shim for WIFI_ConnectAPExt of wifi interface.
erpc_status_t wifi_service::WIFI_ConnectAPExt_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    WIFINetworkParamsExt_t *pxNetworkParamsExt = NULL;
    pxNetworkParamsExt = (WIFINetworkParamsExt_t *) erpc_malloc(sizeof(WIFINetworkParamsExt_t));
    if (pxNetworkParamsExt == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    WIFIReturnCode_t result;

    // startReadMessage() was already called before this shim was invoked.

    read_WIFINetworkParamsExt_t_struct(codec, pxNetworkParamsExt);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->WIFI_ConnectAPExt(pxNetworkParamsExt);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, wifi_interface::m_serviceId, wifi_interface::m_WIFI_ConnectAPExtId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    erpc_free(pxNetworkParamsExt);

    return err;
}

// Server shim for WIFI_Disconnect of wifi interface.
erpc_status_t wifi_service::WIFI_Disconnect_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    WIFIReturnCode_t result;

    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->WIFI_Disconnect();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, wifi_interface::m_serviceId, wifi_interface::m_WIFI_DisconnectId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    return err;
}

// Server shim for WIFI_GetConnectionInfo of wifi interface.
erpc_status_t wifi_service::WIFI_GetConnectionInfo_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    WIFIConnectionInfo_t *pxConnectionInfo = NULL;
    WIFIReturnCode_t result;

    // startReadMessage() was already called before this shim was invoked.

    pxConnectionInfo = (WIFIConnectionInfo_t *) erpc_malloc(sizeof(WIFIConnectionInfo_t));
    if (pxConnectionInfo == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->WIFI_GetConnectionInfo(pxConnectionInfo);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, wifi_interface::m_serviceId, wifi_interface::m_WIFI_GetConnectionInfoId, sequence);

        write_WIFIConnectionInfo_t_struct(codec, pxConnectionInfo);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    erpc_free(pxConnectionInfo);

    return err;
}
